name=MQLib
version=1.0.0
author=Martynov Labs
maintainer=Martynov Labs
sentence=Library for MQ gas sensors
paragraph=Provides basic support for MQ5 and MQ7 sensors.
category=Sensors
url=https://example.com
architectures=*
